export default {
  loading: true,
  posts: [],
  currentView: 'operacionLiquidacion',
  servicio: null,
  crearOperacionConcertada: null,
  listarOperacion: null,
  listaOperaciones: [],
  listaDivisas: [],
  calendario: [],
  quoteRequest: null,
  operacionConcertada: null,
  listaOrigen: [],
  listaDestino: [],
};
