export default {
  loading: true,
  posts: [],
  currentView: 'operacionesFx',
  servicio: null,
  crearOperacionConcertada: null,
  listarOperacion: null,
  listaOperaciones: [],
  listaDivisas: [],
  calendario: [],
  quoteRequest: null,
  operacionConcertada: null,
  listaOrigen: [],
  listaDestino: [],
  mapClientLogeo: {
    alias: 'f3853',
    CUI: '00007391',
    updatePassword: 'true',
    aaplicationCode: 'INVEXCOM_CTES',
    userPassword: 'userPassword',
    email: 'jgonzales@invex.com',
    tokenStatus: 'Activo',
    dateLastAccess: '2022-03-04T10:10:23.01',
    internetFolio: '3853',
    passwordAttemp: '0',
    transferLimitMXP: '450000',
    transferLimitUSD: '0',
    userLogin: '',
    userProfile: 'Operacion',
    product: 'IE',
    tokenSerie: '000408413523',
    requestTokenChange: 'false',
    maximunTimeSession: '5',
    personType: 'Fisica',
    tokenTyoe: 'Virtual',
    tokenExpire: 'false',
    visualizeSetLimits: 'false',
    visualizeStatementAccounts: 'false',
    Notification: {
      notificationID: 'A0006',
      notificationDescription: 'DespliegaValidacionToken',
    },
    user360T: 'INVEXCOMP.TEST',
    portFolio: 'BCA-PRIV',
    twoWay: 'false',
  },
};
